#!/bin/sh

# Usage: volume up
#        volume down
#        volume toggle

case $1 in
	"up")     ponymix increase 5 ;;
	"down")   ponymix decrease 5 ;;
	"toggle") ponymix toggle     ;;
esac

if $(ponymix is-muted); then
	echo "M" > $HOME/.volume
else
	echo $(ponymix get-volume) > $HOME/.volume
fi
